'use client';

import { useState } from 'react';
import { FileText, Download, Share2, Check, Copy } from 'lucide-react';
import type { AnalysisResult } from '@/lib/types';
import { formatDate, getScoreColor, getCategoryLabel, generateActionPlan, generateShareToken } from '@/lib/utils';

interface Props {
  result: AnalysisResult;
  locale: 'en' | 'ar';
}

export function PdfReport({ result, locale }: Props) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [shareLink, setShareLink] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      // In production, this would generate a real PDF using jsPDF
      // For now, we simulate the download
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Create a simple text-based report
      const actionPlan = generateActionPlan(result.findings);
      let report = `SMART LAND - AI DIGITAL AUDIT REPORT\n`;
      report += `================================\n\n`;
      report += `URL: ${result.url}\n`;
      report += `Date: ${formatDate(result.date, locale)}\n`;
      report += `Overall Score: ${result.overallScore}/100\n\n`;
      report += `SCORE BREAKDOWN\n`;
      report += `----------------\n`;
      const categories = ['seo', 'performance', 'accessibility', 'security', 'content', 'technical'] as const;
      for (const cat of categories) {
        report += `${getCategoryLabel(cat, locale)}: ${result.scores[cat].score}/100\n`;
      }
      report += `\nSTRENGTHS\n`;
      report += `----------\n`;
      result.strengths.forEach(s => report += `✓ ${s}\n`);
      report += `\nWEAKNESSES\n`;
      report += `-----------\n`;
      result.weaknesses.forEach(w => report += `✗ ${w}\n`);
      report += `\nCRITICAL ISSUES\n`;
      report += `----------------\n`;
      result.criticalIssues.forEach(f => report += `! ${f.issue} (${f.severity})\n`);
      report += `\nACTION PLAN\n`;
      report += `------------\n`;
      actionPlan.forEach((item, i) => {
        report += `${i + 1}. [${item.priority.toUpperCase()}] ${item.issue}\n`;
        report += `   Action: ${item.action}\n`;
        report += `   Impact: ${item.expectedImpact}\n\n`;
      });
      report += `\nMETHODOLOGY & DATA LIMITATIONS\n`;
      report += `-------------------------------\n`;
      report += `Analysis based on publicly available data only.\n`;
      report += `Results reflect the state of the analyzed URL at the time of analysis.\n`;
      report += `Some insights are inferred based on established best practices.\n\n`;
      report += `Generated by Smart Land - AI Digital Audit Platform\n`;

      // Download as text file (in production, this would be PDF)
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `smart-land-audit-${result.id.slice(0, 8)}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
    setIsGenerating(false);
  };

  const handleShare = () => {
    const token = generateShareToken();
    const link = `${window.location.origin}/report/${token}`;
    setShareLink(link);
  };

  const handleCopyLink = () => {
    if (shareLink) {
      navigator.clipboard.writeText(shareLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="glass-card rounded-xl p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-smart-dark-3 flex items-center justify-center">
            <FileText className="w-5 h-5 text-smart-gold" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-white">
              {locale === 'ar' ? 'تقرير التدقيق' : 'Audit Report'}
            </h3>
            <p className="text-xs text-smart-gray">
              {locale === 'ar' ? 'تقرير احترافي قابل للمشاركة' : 'Professional shareable report'}
            </p>
          </div>
        </div>
      </div>

      {/* Report Preview */}
      <div className="bg-smart-black rounded-xl p-4 mb-6 border border-smart-dark-3">
        <div className="text-center mb-4">
          <p className="text-xs text-smart-gold font-semibold mb-1">
            SMART LAND
          </p>
          <p className="text-lg font-bold gold-gradient-text">
            {locale === 'ar' ? 'تقرير التدقيق الرقمي' : 'Digital Audit Report'}
          </p>
        </div>

        <div className="space-y-2 text-xs">
          <div className="flex justify-between">
            <span className="text-smart-gray">{locale === 'ar' ? 'الرابط' : 'URL'}:</span>
            <span className="text-white truncate max-w-[200px]">{result.url}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-smart-gray">{locale === 'ar' ? 'التاريخ' : 'Date'}:</span>
            <span className="text-white">{formatDate(result.date, locale)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-smart-gray">{locale === 'ar' ? 'النتيجة' : 'Score'}:</span>
            <span className={`font-bold ${getScoreColor(result.overallScore)}`}>
              {result.overallScore}/100
            </span>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={handleDownload}
          disabled={isGenerating}
          className="btn-gold flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm disabled:opacity-50"
        >
          <Download className="w-4 h-4" />
          {isGenerating
            ? (locale === 'ar' ? 'جارٍ التوليد...' : 'Generating...')
            : (locale === 'ar' ? 'تحميل PDF' : 'Download PDF')}
        </button>
        
        <button
          onClick={handleShare}
          className="btn-gold-outline flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm"
        >
          <Share2 className="w-4 h-4" />
          {locale === 'ar' ? 'مشاركة التقرير' : 'Share Report'}
        </button>
      </div>

      {/* Share Link */}
      {shareLink && (
        <div className="mt-4 p-3 rounded-lg bg-smart-dark-3/50 border border-smart-dark-3">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs text-smart-gray truncate">{shareLink}</p>
            <button
              onClick={handleCopyLink}
              className="flex-shrink-0 p-1.5 rounded-lg hover:bg-white/5 text-smart-gold transition-colors"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
          <p className="text-xs text-smart-gray-dark mt-1">
            {locale === 'ar' ? 'الرابط صالح لمدة 7 أيام' : 'Link expires in 7 days'}
          </p>
        </div>
      )}
    </div>
  );
}