"use client"

import { jsPDF } from "jspdf"
import html2canvas from "html2canvas-pro"

interface PDFData {
  title: string
  date: string
  score: number
  metrics: { label: string; value: string }[]
  issues: { type: string; message: string }[]
  recommendations: string[]
  language?: string
}

function detectBrowserLanguage(): string {
  if (typeof window === "undefined") return "en"
  const browserLang = navigator.language || (navigator as any).userLanguage || "en"
  const lang = browserLang.split("-")[0]
  const supportedLangs = ["ar", "en", "fr", "de", "es", "tr", "ur"]
  return supportedLangs.includes(lang) ? lang : "en"
}

const labels = {
  reportTitle: "Analysis Report",
  score: "Score",
  metrics: "Metrics",
  issues: "Issues",
  recommendations: "Recommendations",
  date: "Date",
  critical: "Critical",
  warning: "Warning",
  info: "Info",
  noIssues: "No issues found",
  noRecommendations: "No recommendations",
  generatedBy: "Generated by Smart Land",
}

export async function generatePDF(data: PDFData): Promise<void> {
  const container = document.createElement("div")
  container.style.position = "absolute"
  container.style.left = "-9999px"
  container.style.top = "0"
  container.style.width = "794px"
  container.style.fontFamily = "Arial, sans-serif"
  container.style.direction = "ltr"
  container.style.textAlign = "left"
  container.style.background = "#ffffff"
  container.style.color = "#111827"
  container.style.lineHeight = "1.6"

  const scoreColor = data.score >= 80 ? "#22c55e" : data.score >= 50 ? "#f59e0b" : "#ef4444"

  // Header
  const header = document.createElement("div")
  header.style.cssText = "background:linear-gradient(135deg,#1f2937,#374151);color:white;padding:30px;text-align:center;"
  
  const h1 = document.createElement("h1")
  h1.style.cssText = "font-size:24px;font-weight:700;margin-bottom:8px;"
  h1.innerText = labels.reportTitle
  header.appendChild(h1)

  const dateDiv = document.createElement("div")
  dateDiv.style.cssText = "font-size:13px;opacity:0.8;"
  dateDiv.innerText = `${labels.date}: ${data.date}`
  header.appendChild(dateDiv)

  container.appendChild(header)

  // Score Card
  const scoreCard = document.createElement("div")
  scoreCard.style.cssText = `background:#f9fafb;border:2px solid ${scoreColor};border-radius:12px;padding:24px;margin:24px;text-align:center;`

  const scoreValue = document.createElement("div")
  scoreValue.style.cssText = `font-size:48px;font-weight:700;color:${scoreColor};`
  scoreValue.innerText = `${data.score}%`
  scoreCard.appendChild(scoreValue)

  const scoreLabel = document.createElement("div")
  scoreLabel.style.cssText = "font-size:14px;color:#6b7280;margin-top:4px;"
  scoreLabel.innerText = labels.score
  scoreCard.appendChild(scoreLabel)

  container.appendChild(scoreCard)

  // Metrics Section
  const metricsSection = document.createElement("div")
  metricsSection.style.cssText = "margin:24px;padding:20px;background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;"

  const metricsTitle = document.createElement("div")
  metricsTitle.style.cssText = "font-size:16px;font-weight:600;color:#1f2937;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #f3f4f6;"
  metricsTitle.innerText = labels.metrics
  metricsSection.appendChild(metricsTitle)

  if (data.metrics?.length) {
    data.metrics.forEach(m => {
      const row = document.createElement("div")
      row.style.cssText = "display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #e5e7eb;"

      const label = document.createElement("span")
      label.style.color = "#6b7280"
      label.innerText = m.label

      const value = document.createElement("span")
      value.style.cssText = "font-weight:600;color:#111827;"
      value.innerText = m.value

      row.appendChild(label)
      row.appendChild(value)
      metricsSection.appendChild(row)
    })
  } else {
    const empty = document.createElement("p")
    empty.style.color = "#9ca3af"
    empty.innerText = labels.noIssues
    metricsSection.appendChild(empty)
  }
  container.appendChild(metricsSection)

  // Issues Section
  const issuesSection = document.createElement("div")
  issuesSection.style.cssText = "margin:24px;padding:20px;background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;"

  const issuesTitle = document.createElement("div")
  issuesTitle.style.cssText = "font-size:16px;font-weight:600;color:#1f2937;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #f3f4f6;"
  issuesTitle.innerText = labels.issues
  issuesSection.appendChild(issuesTitle)

  if (data.issues?.length) {
    data.issues.forEach(i => {
      const typeColor = i.type === "critical" ? "#ef4444" : i.type === "warning" ? "#f59e0b" : "#3b82f6"

      const row = document.createElement("div")
      row.style.cssText = `display:flex;align-items:start;gap:8px;padding:8px;margin-bottom:6px;background:#f9fafb;border-radius:6px;border-left:3px solid ${typeColor};`

      const typeSpan = document.createElement("span")
      typeSpan.style.cssText = `color:${typeColor};font-weight:600;font-size:12px;text-transform:uppercase;`
      typeSpan.innerText = (labels as any)[i.type] || i.type

      const msgSpan = document.createElement("span")
      msgSpan.style.cssText = "color:#374151;font-size:13px;"
      msgSpan.innerText = i.message

      row.appendChild(typeSpan)
      row.appendChild(msgSpan)
      issuesSection.appendChild(row)
    })
  } else {
    const empty = document.createElement("p")
    empty.style.color = "#9ca3af"
    empty.innerText = labels.noIssues
    issuesSection.appendChild(empty)
  }
  container.appendChild(issuesSection)

  // Recommendations Section
  const recSection = document.createElement("div")
  recSection.style.cssText = "margin:24px;padding:20px;background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;"

  const recTitle = document.createElement("div")
  recTitle.style.cssText = "font-size:16px;font-weight:600;color:#1f2937;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #f3f4f6;"
  recTitle.innerText = labels.recommendations
  recSection.appendChild(recTitle)

  if (data.recommendations?.length) {
    data.recommendations.forEach(r => {
      const row = document.createElement("div")
      row.style.cssText = "display:flex;align-items:start;gap:8px;padding:8px;margin-bottom:6px;background:#ecfdf5;border-radius:6px;"

      const check = document.createElement("span")
      check.style.cssText = "color:#22c55e;font-size:16px;"
      check.innerText = "OK"

      const text = document.createElement("span")
      text.style.cssText = "color:#065f46;font-size:13px;"
      text.innerText = r

      row.appendChild(check)
      row.appendChild(text)
      recSection.appendChild(row)
    })
  } else {
    const empty = document.createElement("p")
    empty.style.color = "#9ca3af"
    empty.innerText = labels.noRecommendations
    recSection.appendChild(empty)
  }
  container.appendChild(recSection)

  // Footer
  const footer = document.createElement("div")
  footer.style.cssText = "background:#f9fafb;padding:16px;text-align:center;font-size:12px;color:#9ca3af;margin-top:24px;"
  footer.innerText = `${labels.generatedBy} | Smart Land © ${new Date().getFullYear()}`
  container.appendChild(footer)

  document.body.appendChild(container)

  try {
    await document.fonts.ready

    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: "#ffffff",
      logging: false,
      width: 794,
      windowWidth: 794,
    })

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "px",
      format: [canvas.width, canvas.height],
    })

    pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height)

    const pageHeight = 1123
    let heightLeft = canvas.height
    let position = 0

    if (canvas.height > pageHeight) {
      heightLeft -= pageHeight
      position = -pageHeight

      while (heightLeft > 0) {
        pdf.addPage()
        pdf.addImage(imgData, "PNG", 0, position, canvas.width, canvas.height)
        heightLeft -= pageHeight
        position -= pageHeight
      }
    }

    pdf.save(`smart_land_report_${Date.now()}.pdf`)

  } finally {
    document.body.removeChild(container)
  }
}

export function exportAnalysisPDF(data: Omit<PDFData, "language">): Promise<void> {
  return generatePDF({ ...data, language: detectBrowserLanguage() })
}

export function exportDashboardPDF(data: Omit<PDFData, "language">): Promise<void> {
  return generatePDF({ ...data, language: detectBrowserLanguage() })
}

export async function generatePDFWithLanguage(
  data: Omit<PDFData, "language">,
  language: string
): Promise<void> {
  return generatePDF({ ...data, language })
}