"use client"

import { jsPDF } from "jspdf"
import html2canvas from "html2canvas"

interface PDFData {
  title: string
  date: string
  score: number
  metrics: { label: string; value: string }[]
  issues: { type: string; message: string }[]
  recommendations: string[]
  language?: string // optional — هنكتشفها تلقائي
}

// =====================
// 1. اكتشاف لغة المتصفح
// =====================
function detectBrowserLanguage(): string {
  if (typeof window === "undefined") return "en"
  
  const browserLang = navigator.language || (navigator as any).userLanguage || "en"
  const lang = browserLang.split("-")[0] // "ar-SA" → "ar"
  
  // اللغات المدعومة
  const supportedLangs = ["ar", "en", "fr", "de", "es", "tr", "ur"]
  return supportedLangs.includes(lang) ? lang : "en"
}

// =====================
// 2. ترجمة النصوص
// =====================
const translations: Record<string, Record<string, string>> = {
  ar: {
    reportTitle: "تقرير التحليل",
    score: "النتيجة",
    metrics: "المقاييس",
    issues: "المشاكل",
    recommendations: "التوصيات",
    date: "التاريخ",
    critical: "حرج",
    warning: "تحذير",
    info: "معلومة",
    noIssues: "لا توجد مشاكل",
    noRecommendations: "لا توجد توصيات",
    generatedBy: "تم إنشاء هذا التقرير بواسطة سمارت لاند",
  },
  en: {
    reportTitle: "Analysis Report",
    score: "Score",
    metrics: "Metrics",
    issues: "Issues",
    recommendations: "Recommendations",
    date: "Date",
    critical: "Critical",
    warning: "Warning",
    info: "Info",
    noIssues: "No issues found",
    noRecommendations: "No recommendations",
    generatedBy: "Generated by Smart Land",
  },
  fr: {
    reportTitle: "Rapport d'Analyse",
    score: "Score",
    metrics: "Métriques",
    issues: "Problèmes",
    recommendations: "Recommandations",
    date: "Date",
    critical: "Critique",
    warning: "Avertissement",
    info: "Info",
    noIssues: "Aucun problème",
    noRecommendations: "Aucune recommandation",
    generatedBy: "Généré par Smart Land",
  },
  de: {
    reportTitle: "Analysebericht",
    score: "Ergebnis",
    metrics: "Metriken",
    issues: "Probleme",
    recommendations: "Empfehlungen",
    date: "Datum",
    critical: "Kritisch",
    warning: "Warnung",
    info: "Info",
    noIssues: "Keine Probleme",
    noRecommendations: "Keine Empfehlungen",
    generatedBy: "Erstellt von Smart Land",
  },
  es: {
    reportTitle: "Informe de Análisis",
    score: "Puntuación",
    metrics: "Métricas",
    issues: "Problemas",
    recommendations: "Recomendaciones",
    date: "Fecha",
    critical: "Crítico",
    warning: "Advertencia",
    info: "Info",
    noIssues: "Sin problemas",
    noRecommendations: "Sin recomendaciones",
    generatedBy: "Generado por Smart Land",
  },
  tr: {
    reportTitle: "Analiz Raporu",
    score: "Puan",
    metrics: "Metrikler",
    issues: "Sorunlar",
    recommendations: "Öneriler",
    date: "Tarih",
    critical: "Kritik",
    warning: "Uyarı",
    info: "Bilgi",
    noIssues: "Sorun bulunamadı",
    noRecommendations: "Öneri bulunamadı",
    generatedBy: "Smart Land tarafından oluşturuldu",
  },
  ur: {
    reportTitle: "تجزیاتی رپورٹ",
    score: "اسکور",
    metrics: "میٹرکس",
    issues: "مسائل",
    recommendations: "سفارشات",
    date: "تاریخ",
    critical: "سنگین",
    warning: "انتباہ",
    info: "معلومات",
    noIssues: "کوئی مسئلہ نہیں",
    noRecommendations: "کوئی سفارش نہیں",
    generatedBy: "اسمارٹ لینڈ کے ذریعے تیار کردہ",
  },
}

function getTranslation(lang: string, key: string): string {
  return translations[lang]?.[key] || translations["en"][key]
}

// =====================
// 3. توليد HTML للـ PDF
// =====================
function generateHTMLContent(data: PDFData, lang: string): string {
  const t = (key: string) => getTranslation(lang, key)
  const isRTL = ["ar", "ur"].includes(lang)
  const dir = isRTL ? "rtl" : "ltr"
  const align = isRTL ? "right" : "left"
  const scoreColor = data.score >= 80 ? "#22c55e" : data.score >= 50 ? "#f59e0b" : "#ef4444"

  const metricsHTML = data.metrics?.length
    ? data.metrics.map(m => `
        <div style="display:flex; justify-content:space-between; padding:8px 0; border-bottom:1px solid #e5e7eb;">
          <span style="color:#6b7280;">${m.label}</span>
          <span style="font-weight:600; color:#111827;">${m.value}</span>
        </div>
      `).join("")
    : `<p style="color:#9ca3af;">${t("noIssues")}</p>`

  const issuesHTML = data.issues?.length
    ? data.issues.map(i => {
        const typeColor = i.type === "critical" ? "#ef4444" : i.type === "warning" ? "#f59e0b" : "#3b82f6"
        return `
          <div style="display:flex; align-items:start; gap:8px; padding:8px; margin-bottom:6px; background:#f9fafb; border-radius:6px; border-${isRTL ? "right" : "left"}:3px solid ${typeColor};">
            <span style="color:${typeColor}; font-weight:600; font-size:12px; text-transform:uppercase;">${t(i.type) || i.type}</span>
            <span style="color:#374151; font-size:13px;">${i.message}</span>
          </div>
        `
      }).join("")
    : `<p style="color:#9ca3af;">${t("noIssues")}</p>`

  const recommendationsHTML = data.recommendations?.length
    ? data.recommendations.map(r => `
        <div style="display:flex; align-items:start; gap:8px; padding:8px; margin-bottom:6px; background:#ecfdf5; border-radius:6px;">
          <span style="color:#22c55e; font-size:16px;">✓</span>
          <span style="color:#065f46; font-size:13px;">${r}</span>
        </div>
      `).join("")
    : `<p style="color:#9ca3af;">${t("noRecommendations")}</p>`

  return `
    <!DOCTYPE html>
    <html dir="${dir}" lang="${lang}">
    <head>
      <meta charset="UTF-8">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Naskh+Arabic:wght@400;500;600;700&family=Noto+Nastaliq+Urdu:wght@400;500;600;700&display=swap');
        
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
          font-family: ${lang === "ar" ? "'Noto Naskh Arabic', serif" : lang === "ur" ? "'Noto Nastaliq Urdu', serif" : "'Inter', sans-serif"};
          background: #ffffff;
          color: #111827;
          line-height: 1.6;
          direction: ${dir};
          text-align: ${align};
          padding: 0;
        }
        
        .header {
          background: linear-gradient(135deg, #1f2937 0%, #374151 100%);
          color: white;
          padding: 30px;
          text-align: center;
        }
        
        .header h1 {
          font-size: 24px;
          font-weight: 700;
          margin-bottom: 8px;
        }
        
        .header .date {
          font-size: 13px;
          opacity: 0.8;
        }
        
        .score-card {
          background: #f9fafb;
          border: 2px solid ${scoreColor};
          border-radius: 12px;
          padding: 24px;
          margin: 24px;
          text-align: center;
        }
        
        .score-value {
          font-size: 48px;
          font-weight: 700;
          color: ${scoreColor};
        }
        
        .score-label {
          font-size: 14px;
          color: #6b7280;
          margin-top: 4px;
        }
        
        .section {
          margin: 24px;
          padding: 20px;
          background: #ffffff;
          border: 1px solid #e5e7eb;
          border-radius: 8px;
        }
        
        .section-title {
          font-size: 16px;
          font-weight: 600;
          color: #1f2937;
          margin-bottom: 12px;
          padding-bottom: 8px;
          border-bottom: 2px solid #f3f4f6;
        }
        
        .footer {
          background: #f9fafb;
          padding: 16px;
          text-align: center;
          font-size: 12px;
          color: #9ca3af;
          margin-top: 24px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${t("reportTitle")}</h1>
        <div class="date">${t("date")}: ${data.date}</div>
      </div>
      
      <div class="score-card">
        <div class="score-value">${data.score}%</div>
        <div class="score-label">${t("score")}</div>
      </div>
      
      <div class="section">
        <div class="section-title">${t("metrics")}</div>
        ${metricsHTML}
      </div>
      
      <div class="section">
        <div class="section-title">${t("issues")}</div>
        ${issuesHTML}
      </div>
      
      <div class="section">
        <div class="section-title">${t("recommendations")}</div>
        ${recommendationsHTML}
      </div>
      
      <div class="footer">
        ${t("generatedBy")} | Smart Land © ${new Date().getFullYear()}
      </div>
    </body>
    </html>
  `
}

// =====================
// 4. توليد الـ PDF
// =====================
export async function generatePDF(data: PDFData): Promise<void> {
  const lang = data.language || detectBrowserLanguage()
  const isRTL = ["ar", "ur"].includes(lang)
  
  // إنشاء container مخفي
  const container = document.createElement("div")
  container.style.position = "absolute"
  container.style.left = "-9999px"
  container.style.top = "0"
  container.style.width = "794px" // A4 width at 96 DPI
  container.innerHTML = generateHTMLContent(data, lang)
  document.body.appendChild(container)

  try {
    // انتظار تحميل الخطوط
    await document.fonts.ready

    // تحويل HTML لـ canvas
    const canvas = await html2canvas(container, {
      scale: 2, // جودة عالية
      useCORS: true,
      allowTaint: true,
      backgroundColor: "#ffffff",
      logging: false,
      width: 794,
      windowWidth: 794,
    })

    // إنشاء PDF
    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "px",
      format: [canvas.width, canvas.height],
    })

    pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height)

    // لو المحتوى طويل — نضيف صفحات
    const pageHeight = 1123 // A4 height at 96 DPI
    let heightLeft = canvas.height
    let position = 0

    if (canvas.height > pageHeight) {
      heightLeft -= pageHeight
      position = -pageHeight

      while (heightLeft > 0) {
        pdf.addPage()
        pdf.addImage(imgData, "PNG", 0, position, canvas.width, canvas.height)
        heightLeft -= pageHeight
        position -= pageHeight
      }
    }

    // حفظ الملف
    const filename = `${data.title.replace(/[^a-zA-Z0-9\u0600-\u06FF]/g, "_")}_${lang}.pdf`
    pdf.save(filename)

  } finally {
    // تنظيف
    document.body.removeChild(container)
  }
}

// =====================
// 5. دوال التصدير
// =====================
export function exportAnalysisPDF(data: Omit<PDFData, "language">): Promise<void> {
  return generatePDF({ ...data, language: detectBrowserLanguage() })
}

export function exportDashboardPDF(data: Omit<PDFData, "language">): Promise<void> {
  return generatePDF({ ...data, language: detectBrowserLanguage() })
}

// =====================
// 6. تبديل اللغة يدوي
// =====================
export async function generatePDFWithLanguage(
  data: Omit<PDFData, "language">,
  language: string
): Promise<void> {
  return generatePDF({ ...data, language })
}