"use client";

import { usePathname } from "next/navigation";
import { Shield, FileText, ArrowLeft, CheckCircle, AlertTriangle, Scale, UserCheck, Ban, Mail, Lock } from "lucide-react";
import Link from "next/link";

const translations: Record<string, Record<string, string>> = {
  en: {
    title: "Terms of Service",
    subtitle: "Terms and conditions governing your use of Smart Land",
    lastUpdated: "Last Updated: July 2026",
    intro: "Please read these Terms of Service ('Terms', 'Terms of Service') carefully before using the Smart Land platform operated by Smart Land. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.",
    section1: "1. Acceptance of Terms",
    section1Content: "By accessing or using Smart Land, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service. We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of the Service after any changes constitutes acceptance of the new Terms.",
    section2: "2. Description of Service",
    section2Content: "Smart Land provides AI-powered digital audit analysis for websites and social media profiles. The Service analyzes publicly available data from URLs you submit and provides analysis results, insights, and recommendations. The analysis is based on publicly accessible data only and does not access password-protected or private content.",
    section3: "3. User Obligations",
    section3Content: "You agree to: provide accurate information when using our contact forms; not use the Service for any unlawful purpose; not attempt to disrupt or compromise the Service; not submit URLs containing malicious content; not use automated tools to abuse the Service; and respect the intellectual property rights of Smart Land and third parties.",
    section4: "4. Intellectual Property",
    section4Content: "The Smart Land platform, including its design, code, graphics, logos, and original content, is owned by Smart Land and protected by applicable intellectual property laws. Analysis results generated by the Service are provided for your personal use. You may not reproduce, distribute, or create derivative works without our prior written consent.",
    section5: "5. Disclaimer of Warranties",
    section5Content: "The Service is provided on an 'AS IS' and 'AS AVAILABLE' basis without warranties of any kind, either express or implied. Smart Land does not guarantee that: the Service will be uninterrupted or error-free; the results will be accurate or complete; the quality of any products, services, or information obtained through the Service will meet your expectations; or any errors in the Service will be corrected.",
    section6: "6. Limitation of Liability",
    section6Content: "In no event shall Smart Land, its directors, employees, partners, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service. This includes, without limitation, loss of profits, data, use, goodwill, or other intangible losses. Your sole remedy for dissatisfaction with the Service is to stop using it.",
    section7: "7. Privacy and Data Use",
    section7Content: "Your use of Smart Land is also governed by our Privacy Policy, which explains how we collect, use, and protect your information. By using the Service, you consent to our data practices as described in the Privacy Policy. Analysis results are stored locally on your device. We do not store analysis data on our servers.",
    section8: "8. Third-Party Services",
    section8Content: "Smart Land may integrate with or reference third-party services such as Google Analytics. We are not responsible for the content, privacy policies, or practices of any third-party services. Your use of third-party services is subject to their respective terms and conditions.",
    section9: "9. Prohibited Uses",
    section9Content: "You agree not to: use the Service for any illegal activity; attempt to gain unauthorized access to any part of the Service; interfere with the proper working of the Service; bypass any measures used to prevent or restrict access to the Service; use the Service to analyze URLs that you do not have the right to analyze; or use the Service in any way that violates applicable laws or regulations.",
    section10: "10. Termination",
    section10Content: "We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. All provisions of the Terms which by their nature should survive termination shall survive.",
    section11: "11. Governing Law",
    section11Content: "These Terms shall be governed and construed in accordance with the laws of Egypt, without regard to its conflict of law provisions. Any disputes arising from these Terms shall be resolved in the courts of Egypt.",
    section12: "12. Changes to Terms",
    section12Content: "We reserve the right to modify or replace these Terms at any time. We will provide notice of material changes by posting the new Terms on this page. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised Terms.",
    section13: "13. Contact Information",
    section13Content: "If you have any questions about these Terms, please contact us at elsayedsameh803@gmail.com or via WhatsApp at 01272097150.",
    agree: "By using Smart Land, you acknowledge that you have read and understood these Terms of Service.",
    backToHome: "Back to Home",
  },
  ar: {
    title: "شروط الخدمة",
    subtitle: "الشروط والأحكام التي تحكم استخدامك لسمارت لاند",
    lastUpdated: "آخر تحديث: يوليو 2026",
    intro: "يرجى قراءة شروط الخدمة هذه ('الشروط') بعناية قبل استخدام منصة سمارت لاند التي تديرها سمارت لاند. دخولك واستخدامك للخدمة مشروط بقبولك والامتثال لهذه الشروط. تنطبق هذه الشروط على جميع الزوار والمستخدمين والآخرين الذين يصلون أو يستخدمون الخدمة.",
    section1: "1. قبول الشروط",
    section1Content: "باستخدام سمارت لاند، فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق على أي جزء من الشروط، فلا يجوز لك الوصول إلى الخدمة. نحتفظ بالحق في تحديث أو تعديل هذه الشروط في أي وقت دون إشعار مسبق. استمرار استخدامك للخدمة بعد أي تغييرات يشكل قبولاً للشروط الجديدة.",
    section2: "2. وصف الخدمة",
    section2Content: "تقدم سمارت لاند تحليلاً رقمياً مدعوماً بالذكاء الاصطناعي للمواقع الإلكترونية وحسابات التواصل الاجتماعي. تقوم الخدمة بتحليل البيانات المتاحة للعموم من الروابط التي ترسلها وتقدم نتائج التحليل والرؤى والتوصيات. يعتمد التحليل على البيانات المتاحة للعموم فقط ولا يصل إلى المحتوى المحمي بكلمة مرور أو الخاص.",
    section3: "3. التزامات المستخدم",
    section3Content: "أنت توافق على: تقديم معلومات دقيقة عند استخدام نماذج الاتصال الخاصة بنا؛ عدم استخدام الخدمة لأي غرض غير قانوني؛ عدم محاولة تعطيل أو اختراق الخدمة؛ عدم إرسال روابط تحتوي على محتوى ضار؛ عدم استخدام أدوات آلية لإساءة استخدام الخدمة؛ واحترام حقوق الملكية الفكرية لسمارت لاند والأطراف الثالثة.",
    section4: "4. الملكية الفكرية",
    section4Content: "منصة سمارت لاند، بما في ذلك تصميمها ورمزها ورسوماتها وشعاراتها ومحتواها الأصلي، مملوكة لسمارت لاند ومحمية بموجب قوانين الملكية الفكرية المعمول بها. نتائج التحليل التي تولدها الخدمة مقدمة لاستخدامك الشخصي. لا يجوز لك نسخ أو توزيع أو إنشاء أعمال مشتقة دون موافقتنا الخطية المسبقة.",
    section5: "5. إخلاء المسؤولية عن الضمانات",
    section5Content: "تُقدم الخدمة على أساس 'كما هي' و 'حسب التوفر' دون ضمانات من أي نوع، صريحة أو ضمنية. لا تضمن سمارت لاند أن: الخدمة ستكون دون انقطاع أو خالية من الأخطاء؛ ستكون النتائج دقيقة أو كاملة؛ جودة أي منتجات أو خدمات أو معلومات يتم الحصول عليها من خلال الخدمة ستلبي توقعاتك؛ أو سيتم تصحيح أي أخطاء في الخدمة.",
    section6: "6. تحديد المسؤولية",
    section6Content: "لا تتحمل سمارت لاند أو مديروها أو موظفوها أو شركاؤها أو الشركات التابعة لها أي مسؤولية عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية تنشأ عن أو تتعلق باستخدامك للخدمة. يشمل ذلك، على سبيل المثال لا الحصر، فقدان الأرباح أو البيانات أو الاستخدام أو الشهرة أو الخسائر غير الملموسة الأخرى. العلاج الوحيد الخاص بك لعدم الرضا عن الخدمة هو التوقف عن استخدامها.",
    section7: "7. الخصوصية واستخدام البيانات",
    section7Content: "يخضع استخدامك لسمارت لاند أيضاً لسياسة الخصوصية الخاصة بنا، والتي تشرح كيفية جمعنا واستخدامنا وحمايتنا لمعلوماتك. باستخدام الخدمة، فإنك توافق على ممارسات البيانات الخاصة بنا كما هو موصوف في سياسة الخصوصية. يتم تخزين نتائج التحليل محلياً على جهازك. لا نخزن بيانات التحليل على خوادمنا.",
    section8: "8. خدمات الأطراف الثالثة",
    section8Content: "قد تتكامل سمارت لاند مع أو تشير إلى خدمات طرف ثالث مثل Google Analytics. نحن لسنا مسؤولين عن محتوى أو سياسات الخصوصية أو ممارسات أي خدمات طرف ثالث. استخدامك لخدمات الطرف الثالث يخضع لشروطها وأحكامها الخاصة.",
    section9: "9. الاستخدامات المحظورة",
    section9Content: "أنت توافق على عدم: استخدام الخدمة لأي نشاط غير قانوني؛ محاولة الوصول غير المصرح به إلى أي جزء من الخدمة؛ التدخل في العمل السليم للخدمة؛ تجاوز أي تدابير تستخدم لمنع أو تقييد الوصول إلى الخدمة؛ استخدام الخدمة لتحليل روابط لا يحق لك تحليلها؛ أو استخدام الخدمة بأي طريقة تنتهك القوانين أو اللوائح المعمول بها.",
    section10: "10. الإنهاء",
    section10Content: "يجوز لنا إنهاء أو تعليق وصولك إلى الخدمة فوراً، دون إشعار مسبق أو مسؤولية، لأي سبب كان، بما في ذلك على سبيل المثال لا الحصر إذا انتهكت الشروط. عند الإنهاء، سيتوقف حقك في استخدام الخدمة فوراً. جميع أحكام الشروط التي يجب بطبيعتها أن تستمر بعد الإنهاء ستبقى سارية.",
    section11: "11. القانون الحاكم",
    section11Content: "تخضع هذه الشروط وتفسر وفقاً لقوانين مصر، دون اعتبار لأحكام تنازع القوانين. يتم حل أي نزاعات ناشئة عن هذه الشروط في محاكم مصر.",
    section12: "12. التغييرات في الشروط",
    section12Content: "نحتفظ بالحق في تعديل أو استبدال هذه الشروط في أي وقت. سنقدم إشعاراً بالتغييرات الجوهرية عن طريق نشر الشروط الجديدة على هذه الصفحة. من خلال الاستمرار في الوصول إلى خدماتنا أو استخدامها بعد أن تصبح هذه المراجعات سارية المفعول، فإنك توافق على الالتزام بالشروط المنقحة.",
    section13: "13. معلومات الاتصال",
    section13Content: "إذا كانت لديك أي أسئلة حول هذه الشروط، يرجى الاتصال بنا على elsayedsameh803@gmail.com أو عبر واتساب على 01272097150.",
    agree: "باستخدام سمارت لاند، فإنك تقر بأنك قد قرأت وفهمت شروط الخدمة هذه.",
    backToHome: "العودة إلى الرئيسية",
  },
};

export default function TermsPage({ params }: { params: { locale: string } }) {
  const locale = params.locale;
  const isRtl = locale === "ar";
  const t = translations[locale] || translations.en;

  const sections = [
    { icon: FileText, title: t.section1, content: t.section1Content },
    { icon: Shield, title: t.section2, content: t.section2Content },
    { icon: UserCheck, title: t.section3, content: t.section3Content },
    { icon: Scale, title: t.section4, content: t.section4Content },
    { icon: AlertTriangle, title: t.section5, content: t.section5Content },
    { icon: Ban, title: t.section6, content: t.section6Content },
    { icon: Lock, title: t.section7, content: t.section7Content },
    { icon: CheckCircle, title: t.section8, content: t.section8Content },
    { icon: AlertTriangle, title: t.section9, content: t.section9Content },
    { icon: Ban, title: t.section10, content: t.section10Content },
    { icon: Scale, title: t.section11, content: t.section11Content },
    { icon: FileText, title: t.section12, content: t.section12Content },
    { icon: Mail, title: t.section13, content: t.section13Content },
  ];

  return (
    <div className="min-h-screen bg-dark-950" dir={isRtl ? "rtl" : "ltr"}>
      <div className="pt-32 pb-16 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-gold-500/5 via-transparent to-transparent" />
        <div className="max-w-4xl mx-auto text-center">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-gold-500 to-gold-600 flex items-center justify-center mx-auto mb-6">
            <FileText className="w-8 h-8 text-dark-950" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4">{t.title}</h1>
          <p className="text-xl text-dark-300 mb-4">{t.subtitle}</p>
          <p className="text-sm text-dark-500">{t.lastUpdated}</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">
        <div className="p-6 rounded-2xl bg-dark-800/60 border border-gold-500/10 mb-8">
          <p className="text-dark-300 leading-relaxed">{t.intro}</p>
        </div>

        <div className="space-y-6">
          {sections.map((section, i) => (
            <div key={i} className="p-6 rounded-2xl bg-dark-800/60 border border-gold-500/10">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-gold-500/20 to-gold-600/20 flex items-center justify-center shrink-0 mt-1">
                  <section.icon className="w-5 h-5 text-gold-400" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-white mb-3">{section.title}</h2>
                  <p className="text-dark-300 leading-relaxed">{section.content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-8 p-6 rounded-2xl bg-gold-500/5 border border-gold-500/20">
          <p className="text-gold-300 text-center">{t.agree}</p>
        </div>

        <div className="mt-8 text-center">
          <Link href={`/${locale}`} className="inline-flex items-center gap-2 text-gold-400 hover:text-gold-300 transition-colors">
            <ArrowLeft className={`w-4 h-4 ${isRtl ? 'rotate-180' : ''}`} />
            {t.backToHome}
          </Link>
        </div>
      </div>
    </div>
  );
}